### ISSUE TITLE
Reading sparse tiledb array abruptly exits

### ISSUE THREAD

**Issue by weidinger-c** [TileDB-Inc/TileDB-Py#1943] opened 2024-04-04 08:52 UTC
I have a large sparse array with about 400 million entries (3D point entries with x,y,z as dimensions and some point information like intensity, etc. as attributes). Unfortunatley when I want to read the pointcloud with `point_cloud = db.df[:]` the python instance just exits without an error. 
My first thought was not enough memory, but the I have 64GB of memory and during processing it raised to only about 25GB, so I can rule out "out of memory"

I have new insights to this issue: the tiledb query only exits, if I have the following settings for creating the array:

- tiledb.default_ctx({"sm.dedup_coords": "true"})
- allows_duplicates=False,

```
tiledb.default_ctx({"sm.dedup_coords": "true"})

dom = tiledb.Domain(
    tiledb.Dim(
        name="X",
        domain=(np.finfo(np.float64).min, np.finfo(np.float64).max),
        dtype=np.float64,
        filters=filter_list,
    ),
    tiledb.Dim(
        name="Y",
        domain=(np.finfo(np.float64).min, np.finfo(np.float64).max),
        dtype=np.float64,
        filters=filter_list,
    ),
    tiledb.Dim(
        name="Z",
        domain=(np.finfo(np.float64).min, np.finfo(np.float64).max),
        dtype=np.float64,
        filters=filter_list,
    ),
)
# Create schema
schema = tiledb.ArraySchema(
    domain=dom,
    attrs=[
        tiledb.Attr(name="Intensity", dtype=np.uint16),
        tiledb.Attr(name="Label", dtype=np.uint16),
        tiledb.Attr(name="PointId", dtype=np.uint64),
    ],
    cell_order="hilbert",
    tile_order=None,
    capacity=100000,
    sparse=True,
    allows_duplicates=False,
)
# Create the TileDB array
tiledb.SparseArray.create(tiledb_array_name, schema)
```

**Comment by ihnorton** [comment] 2024-04-04 12:07
Hi @weidinger-c, are you able to share any reproduction code? That would help us pinpoint the issue quickly. In any case, we'll try to reproduce with your schema using random data.

**Comment by weidinger-c** [comment] 2024-04-04 12:09
I'll try to upload an example script with some random test file.

**Comment by weidinger-c** [comment] 2024-04-05 05:45
@ihnorton ok, I have made some further tests. It depends on the input data, I now have a set of files where I can reproduce the behaviour. Can I somehow send to them to you?

**Comment by ihnorton** [comment] 2024-04-05 11:51
Thank you, we are investigating.

**Comment by KiterLuc** [comment] 2024-04-30 16:36
@weidinger-c Sorry for the delay. I believe the following PR will solve your issue: https://github.com/TileDB-Inc/TileDB/pull/4924. 

Also, please note that there is something that could be fixed in your schema. For Hilbert, we order the data using a single 64 bits number, and to compute this number, we divide the 64 bits equally amongst the dimensions, then divide the domain of each dimensions into equal buckets. For your case, each dimensions will get 21 bits, so 2097152 buckets. Since domain is going from float min to float max, your buckets will be very large. In the array you shared, every cells will fall in the same bucket, negating the advantage of using Hilbert. I would recommend using tighter bounds on your domain if you already know limits for it.

**Comment by weidinger-c** [comment] 2024-05-01 05:20
Thanks I will try that out.
I only used "Hilbert" and the min/max bounds, because it is done the same way in the PDAL Writer implementation and I thought it should be done like that for 3D point data. Is there some documentation, when to use which cell_order?

**Comment by weidinger-c** [comment] 2024-05-02 10:19
@KiterLuc I now tried out the changes of your PR. 

- Setting the schema to "row-major" works even with domain at min/max values of float.
- Keeping the domain at min/max values of float and using Hilbert still leads to the unwanted exit (shouldn't your PR have fixed that?)
- Setting the domain at the pointcloud min/max values and using Hilbert works

**Comment by KiterLuc** [comment] 2024-05-02 13:07
Thanks @weidinger-c, we have very little documentation on Hilbert. I filed a ticket to get that fixed soon.

On your question in your second message, how did you rebuilt tiledb? It should be fixed.

**Comment by KiterLuc** [comment] 2024-05-02 13:13
I wonder if that doesn't get picked up by the python package you have installed?

**Comment by KiterLuc** [comment] 2024-05-02 13:17
@ihnorton that's not going to work right?

**Comment by eddelbuettel** [comment] 2024-05-02 13:24
@weidinger-c Can try installaing TileDB-Py from source via eg `python3 -m pip install -v -e .`  ?  On my machine that picks up `/usr/local/lib/libtiledb.so` (and not that I did not impose another directory, and `ldconfig` finds it there. You still may need `sudo ldconfig` after the (C++ library) `make install-tiledb` step.

**Comment by weidinger-c** [comment] 2024-05-02 13:59
@eddelbuettel I can try, but I am not sure what should be the aim of this. I have rebuilt a docker image, so there cannot be any remains from previous installations and I can import and use tiledb in python. So I guess there should be nothing wrong with the installation?

**Comment by ihnorton** [comment] 2024-05-03 02:57
@weidinger-c the simplest way to test the latest changes is probably to install a nightly from our conda channel: `conda create -p test1 -c tiledb/label/nightlies tiledb-py` -- this will give you a build of libtiledb and tiledb-py from last night, with the changes @KiterLuc referenced.

**Comment by ihnorton** [comment] 2024-06-15 19:00
@weidinger-c this fix is available in the [latest release](https://pypi.org/project/tiledb/0.30.0/) on PyPI (and conda-forge). I'll close for now, please let us know if not resolved and we'll reopen to investigate.

**Closed by ihnorton** 2024-06-15 19:00 UTC
