### ISSUE TITLE
Data loss when consolidating single-valued timestamp dimension

### ISSUE THREAD

**Issue by gatesn** [TileDB-Inc/TileDB-Py#565] opened 2021-05-12 09:46 UTC
I ran into an issue where running `tiledb.consolidate(...); tiledb.vacuum(...)` deleted all the data from my array. Minimal repro suggests this happens if a timestamp dimension exists with only a single value, although my repro segfaults on read instead of returning an empty array.

tiledb version: 0.8.2
libtiledb version: 2.2.3

```python
array_name = "consolidate_timestamps"

schema = ArraySchema(
    domain=Domain(
        Dim(name='a', domain=(None, None), dtype="datetime64[ms]"),
        Dim(name='b', domain=(0, 1), dtype=np.uint8),
    ),
    attrs=[Attr(dtype=np.int64)],
    sparse=True
)
schema.check()

Array.create(array_name, schema)

with tiledb.open(array_name, mode='w') as A:
    dt = datetime.now()
    A[[dt], [0]] = [0]
    A[[dt], [1]] = [1]

with tiledb.open(array_name, mode='r') as A:
    print(A[:])

tiledb.consolidate(array_name)
with tiledb.open(str(tmpdir), mode='r') as A:
    print(A[:])  # Segfault here

tiledb.vacuum(array_name)
with tiledb.open(str(tmpdir), mode='r') as A:
    print(A[:])
```

**Comment by ihnorton** [comment] 2021-05-12 17:52
Hi @gatesn, thanks for opening the issue - we are investigating.

**Comment by ihnorton** [comment] 2021-05-25 20:28
Slightly updated test script (added imports, made URI match):
```
from tiledb import *
import numpy as np
from datetime import datetime

array_name = "consolidate_timestamps"

schema = ArraySchema(
    domain=Domain(
        Dim(name='a', domain=(None, None), dtype="datetime64[ms]"),
        Dim(name='b', domain=(0, 1), dtype=np.uint8),
    ),
    attrs=[Attr(dtype=np.int64)],
    sparse=True
)
schema.check()

Array.create(array_name, schema)

with tiledb.open(array_name, mode='w') as A:
    dt = datetime.now()
    A[[dt], [0]] = [0]
    A[[dt], [1]] = [1]

with tiledb.open(array_name, mode='r') as A:
    print(A[:])

tiledb.consolidate(array_name)
with tiledb.open(array_name, mode='r') as A:
    print(A[:])  # Segfault here

tiledb.vacuum(array_name)
with tiledb.open(str(tmpdir), mode='r') as A:
    print(A[:])
```

cc @KiterLuc

**Comment by gatesn** [comment] 2021-06-09 16:44
Are you able to confirm a reproduction of this issue? I think I just ran into it again and not really sure how to fix. Can I "undo" a consolidation by carefully deleting fragment files in S3?

**Comment by ihnorton** [comment] 2021-06-09 21:29
Hi @gatesn, apologies for the delay here: yes, I confirmed the issue and there is a TileDB core PR to fix it (https://github.com/TileDB-Inc/TileDB/pull/2303). We weren't able to get that in the initial 2.3.0 release due to the scope of the changes (that PR fixes several other corner cases), but this specific issue is a high priority for a fix as soon as possible.

**Comment by ihnorton** [comment] 2021-06-09 21:34
> Can I "undo" a consolidation by carefully deleting fragment files in S3?

Yes, as long as you have not vacuumed, then you could delete only those newer fragments written during consolidation, along with the `.ok` files.

For example, using the modified version of your script (I posted above), along with a breakpoint before `tiledb.consolidate`, I've listed the output files below. The two initial writes are at `17:27:02`, and the consolidated fragment is written at `17:27:30`:
```
ls -lT consolidate_timestamps
total 16
drwxr-xr-x  6 inorton  wheel  192 Jun  9 17:27:02 2021 __1623274022306_1623274022306_baf5ebd7316b41ba8dfe8213bedc108a_8
-rw-r--r--  1 inorton  wheel    0 Jun  9 17:27:02 2021 __1623274022306_1623274022306_baf5ebd7316b41ba8dfe8213bedc108a_8.ok
drwxr-xr-x  3 inorton  wheel   96 Jun  9 17:27:30 2021 __1623274022306_1623274022312_af3f9452011c45f78fa77c29c351a1b8_8
-rw-r--r--  1 inorton  wheel    0 Jun  9 17:27:30 2021 __1623274022306_1623274022312_af3f9452011c45f78fa77c29c351a1b8_8.ok
-rw-r--r--  1 inorton  wheel  216 Jun  9 17:27:30 2021 __1623274022306_1623274022312_af3f9452011c45f78fa77c29c351a1b8_8.vac
drwxr-xr-x  6 inorton  wheel  192 Jun  9 17:27:02 2021 __1623274022312_1623274022312_3e93b3f3312848c1877cc764edb80308_8
-rw-r--r--  1 inorton  wheel    0 Jun  9 17:27:02 2021 __1623274022312_1623274022312_3e93b3f3312848c1877cc764edb80308_8.ok
-rw-r--r--  1 inorton  wheel  175 Jun  9 17:27:02 2021 __array_schema.tdb
-rw-r--r--  1 inorton  wheel    0 Jun  9 17:27:02 2021 __lock.tdb
drwxr-xr-x  2 inorton  wheel   64 Jun  9 17:27:02 2021 __meta
```

If I delete `__1623274022306_1623274022312_af3f9452011c45f78fa77c29c351a1b8_8` and `__1623274022306_1623274022312_af3f9452011c45f78fa77c29c351a1b8_8.ok` then the array is readable (no segfault).

**Comment by gatesn** [comment] 2021-06-10 08:11
That's great news thank you. And yes that makes sense r.e. fragments, it's good to know there's a way to 'undo' something that renders the array unreadable.

**Comment by ihnorton** [comment] 2021-06-28 13:15
Hi @gatesn, I've just double-checked in the latest TileDB-Py release ([0.9.1](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.9.1)), and the [slightly-modified repro code](https://github.com/TileDB-Inc/TileDB-Py/issues/565#issuecomment-848237133) I posted, based on your code (only modified imports and array path) now completes successfully -- no segfault, and the same data is printed at each step. Please give it a try when you have a chance.

**Comment by gatesn** [comment] 2021-06-28 13:19
Succeeds for me too. Thank you for fixing this up 👍

**Comment by ihnorton** [comment] 2021-06-28 13:20
Great, thanks for confirming, will go ahead and close this (thanks for the fix @KiterLuc!).

**Closed by ihnorton** 2021-06-28 13:20 UTC
