### ISSUE TITLE
Segfault on array_fragments call

### ISSUE THREAD

**Issue by kylemann16** [TileDB-Inc/TileDB-Py#1888] opened 2024-01-12 18:12 UTC
### Description 
On `linux/amd64` architecture, tiledb is failing to access array fragments and handle array creation errors:
- Accessing an array's fragments via `tiledb.array_fragments(tdb_dir)` leads to a `signal 6` abort. 
- Attempting to create an array that has already been created leads to a `signal 11` segfault

### Expected Results
- Correctly access array fragments
- Output an error message without a segfault when I attempt to create an array that already exists

I assume these errors are coming from the base TileDB library, but I'm interacting with them through Python so I'm posting it here. I can move it over to that repo if necessary though!

Reproduction scripts, logs, and environment versions can be found here:
https://gist.github.com/kylemann16/1e4848c48ba81c8fcaa2efb3f0d5fe27

**Comment by ihnorton** [comment] 2024-01-13 03:34
Thanks @kylemann16, we'll take a look. I can reproduce this, but it appears to be linux-specific.

---
sc-39124

**Comment by ihnorton** [comment] 2024-02-02 03:59
AFAICT this was caused by https://github.com/conda-forge/tiledb-feedstock/issues/228 and is now mitigated via pinning; we'll do our best to get a full fix in ASAP, depending on whether the cause is under our control.

**Comment by ihnorton** [comment] 2024-02-11 03:23
- upstream discussion: https://github.com/Azure/azure-sdk-for-cpp/issues/5322 -- there are a number of x-refs there to pinning updates to ensure that (apparently-necessary) rebuilds happen to prevent this in the future.
- further mitigation in tiledb: https://github.com/TileDB-Inc/TileDB/pull/4703

**Comment by ihnorton** [comment] 2024-02-28 16:32
Closing, please let me know if we need to reopen.

**Closed by ihnorton** 2024-02-28 16:32 UTC
